### ISSUE TITLE
2021.3.11f1 Error on Enter Playmode

### ISSUE THREAD

**Issue by M4R5W0N6** [leorid/Unity-HDRP-GPU-View-Cone#2]
Awesome work!

Just wanted to let you know that as of 2021.3.11f1 I'm getting a "**Objects are trying to be loaded during a domain backup. This is not allowed as it will lead to undefined behaviour!**" upon entering playmode with no stack trace, of course. Will investigate further.

**Comment by leorid** [comment]
Can't reproduce in 2021.3.15f1
